Add user evaluation form tests
codescalersinternships/CSHR pull request #201
Opened 2023-08-29 02:54 UTC by aliwaleed1

2023-08-29 15:36 UTC, A-Harby requested changes

2023-08-29 15:36 UTC, A-Harby commented on pages/evaluation.py
> +    # "//a[contains(@href, '/dashboard')]"
Don't forget to review and clean the code from all the unused comments

2023-08-29 15:36 UTC, A-Harby commented on tests/contest.py
> +    driver = webdriver.Edge()
Why are u using Edge and not the chrome?

2023-08-29 15:36 UTC, A-Harby commented on pages/evaluation.py
> +        select_usered.click()
These 4 lines could be shorter into 2 like

```
WebDriverWait(self.browser, 30).until(EC.visibility_of_element_located(self.selected_user))
self.browser.find_element(*Evaluation.selected_user).click()
```

2023-08-29 15:36 UTC, A-Harby commented on tests/test_evaluation.py
> +def to_login(browse):
To_login isn't the best description maybe it would be better like before_test_setup, setup_for_test

2023-08-29 15:36 UTC, A-Harby commented on tests/test_evaluation.py
> +    evaluation_page.click_dashboard_button()
I can see that these lines (maybe more) are repeated in every test, so why not just call them once in the to_login function and return the object

So only this instead of the repeated 3 lines 
`
evaluation_page = to_login(browse)
`
And add this to the to_login
```
evaluation_page = Evaluation(browse)
evaluation_page.click_dashboard_button()
return evaluation_page
```

2023-08-30 06:31 UTC, aliwaleed1 commented on utils/utils.py
> +    scheme = random.choice(["http", "https", "  "])
because , i need generate valid link and invalid ,and then check in test ,if valid must button will clickable .

2023-08-30 06:37 UTC, aliwaleed1 commented on tests/contest.py
> +    driver = webdriver.Edge()
i just try another browser to check the VPN , i changed it  .

2023-08-30 06:40 UTC, aliwaleed1 commented on pages/evaluation.py
> +        select_usered.click()
I split it into more lines because flake extension , need the line be less than 79 character.

2023-11-26 11:56 UTC, closed without merging