Add login page
codescalersinternships/CSHR pull request #281
Opened 2024-01-06 22:26 UTC by zaelgohary

Related issue: https://github.com/codescalers/CSHR/issues/264

2024-01-08 08:03 UTC, Mahmoud-Emad commented
After logging in, I was able to access the login page, also, the sidebar was shown on the same login page, which is weird because it wasn't there before logged in.

- ![image](https://github.com/codescalers/CSHR/assets/57001890/390f410c-90a1-4de9-93f4-2bdf80d0a64e)

also, the password shouldn't be saved as it is in the local storage, save the hash instead.

- ![image](https://github.com/codescalers/CSHR/assets/57001890/a0d5b9b7-443d-4ca4-a943-dbe514324c0a)

let's take care of the responsiveness, we'll access this website from our phones.

- ![image](https://github.com/codescalers/CSHR/assets/57001890/4daa5a33-565d-4655-9ce8-932c4bfd85c1)

2024-01-08 08:40 UTC, Mahmoud-Emad requested changes
Great work :)

2024-01-08 08:40 UTC, Mahmoud-Emad commented on client/src/components/SideDrawer.vue
>          theme="dark"
if it is supposed to be optional, we need to make it configurable.

2024-01-08 08:40 UTC, Mahmoud-Emad commented on client/src/components/SideDrawer.vue
> +import logo from '../assets/cshr_logo.png'
will be better if we used the @ instead of dots in imports?

2024-01-08 08:40 UTC, Mahmoud-Emad commented on client/src/components/SideDrawer.vue
> +    });
Instead of it, you need to decode the user token and check the expiration date if it's lower than the current date.

e.g.

```ts
const checkTokenExpirationMiddleware = store => next => action => {
  const token =
    JSON.parse(localStorage.getItem("user")) &&
    JSON.parse(localStorage.getItem("user"))["token"];
  if (jwtDecode(token).exp < Date.now() / 1000) {
    next(action);
    localStorage.clear();
  }
  next(action);
};
```

2024-01-08 08:40 UTC, Mahmoud-Emad commented on client/src/utils/helpers.ts
> +  (v: string) => !!v || 'E-mmail is required.',
`Email`?

2024-01-08 08:40 UTC, Mahmoud-Emad commented on client/src/utils/helpers.ts
> +  (v: string) => /.+@.+/.test(v) || 'E-mail is not valid.'
is it valid?

![image](https://github.com/codescalers/CSHR/assets/57001890/1ad08ce0-25fa-4d2e-952d-061ebc9b8017)

2024-01-08 08:40 UTC, Mahmoud-Emad commented on client/src/views/LoginView.vue
> +import { emailRules, passwordRules } from '@/utils'
we need to use one pattern to achieve the `clean code`, use `@` instead.

2024-01-08 08:40 UTC, Mahmoud-Emad commented on client/src/views/LoginView.vue
> +        useStorage('user', {email, password}, sessionStorage, { mergeDefaults: true })
You don't hash the password to save the login, isn't it? okay let's see how we can achieve this

The question is: do we have the logic of filling out the form every time the user requests the login page?

if yes, then it will be good to sign it and use the key for the user email since it's unique then save only the email in the local 

we're trying to avoid the [XSS attack](https://www.synopsys.com/glossary/what-is-cross-site-scripting.html#:~:text=Definition,the%20user%20to%20click%20it.)

2024-01-09 08:15 UTC, zaelgohary commented on client/src/views/LoginView.vue
> +        useStorage('user', {email, password}, sessionStorage, { mergeDefaults: true })
I used btoa built-in function in encoding instead.

2024-01-10 13:11 UTC, zaelgohary commented on client/src/components/SideDrawer.vue
>          theme="dark"
Will be optional based on routing now.

2024-01-10 13:14 UTC, zaelgohary commented
@Mahmoud-Emad As for the responsivity, it won't be added to the current milestone.

2024-01-12 15:19 UTC, merged