Adding user's card
codescalersinternships/CSHR pull request #285
Opened 2024-01-10 19:22 UTC by maayarosama

### Related Issues
#270

2024-01-21 08:31 UTC, Mahmoud-Emad commented
I assume this is a 401 error, which means I don't have a valid token. If that's the case, why am I able to access the UI page? Should I go to the login page instead?

- ![image](https://github.com/codescalers/CSHR/assets/57001890/a7d22a47-162f-4884-8552-2e8edcb30f83)
- ![image](https://github.com/codescalers/CSHR/assets/57001890/8c604328-ff10-4469-a36f-6ca73a847888)

2024-01-21 08:55 UTC, Mahmoud-Emad requested changes

2024-01-21 08:55 UTC, Mahmoud-Emad commented on client/src/components/filters.vue
> +          <span>You can change the selected office to discover the team in other offices, current elected office is your
```suggestion
          <span>You can change the selected office to discover the team in other offices, the current selected office is your
```

2024-01-23 12:26 UTC, maayarosama commented
> I assume this is a 401 error, which means I don't have a valid token. If that's the case, why am I able to access the UI page? Should I go to the login page instead?
> 
> * ![image](https://private-user-images.githubusercontent.com/57001890/298370161-a7d22a47-162f-4884-8552-2e8edcb30f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwODIsIm5iZiI6MTcwNjAxMjc4MiwicGF0aCI6Ii81NzAwMTg5MC8yOTgzNzAxNjEtYTdkMjJhNDctMTYyZi00ODg0LTg1NTItMmU4ZWRjYjMwZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMGM4OGNkYTA3MWJlYWQ0ZWZiZTlkY2QwZGNiZmNiNTI5NjVkMzdhZGRkN2Q5ZmM3ZDc0ZjU1OGNjNDE3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vZqWFOdBQloVIieWpcuamSOLHd9e3oLsmVqJbxC2OKE)
> * ![image](https://private-user-images.githubusercontent.com/57001890/298370173-8c604328-ff10-4469-a36f-6ca73a847888.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwODIsIm5iZiI6MTcwNjAxMjc4MiwicGF0aCI6Ii81NzAwMTg5MC8yOTgzNzAxNzMtOGM2MDQzMjgtZmYxMC00NDY5LWEzNmYtNmNhNzNhODQ3ODg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjhjMGRiOGVlZTg4OGU2MDFkNGNhNGE5MTRiYzg3MGZkMDA4NjY2N2FjYTdhZmRlNjE4NWZlMTJiYmYwZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VgQlz1Di0IsQJej6vR_UXgfESYDXpzDCDjP50yRCOiU)
> * ![image](https://private-user-images.githubusercontent.com/57001890/298370321-783ee63c-5d26-423e-b81e-e94f9ab183ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMTMwODIsIm5iZiI6MTcwNjAxMjc4MiwicGF0aCI6Ii81NzAwMTg5MC8yOTgzNzAzMjEtNzgzZWU2M2MtNWQyNi00MjNlLWI4MWUtZTk0ZjlhYjE4M2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDEyMjYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYjgzZGRiYWMxNzcyMDc5MDM1MjFmODFmYzU3Y2M2NjEwNjFkN2I2MzI3ZWFmYjc3NWQ1MjNhNDI1NWFjZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tpf1KeVeFu9QXc5MxOw6xFPY5uaPSBwS21A04u7Xc1s)

not reproducable

2024-01-23 21:44 UTC, Mahmoud-Emad requested changes
Great work ya Mayar

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/filters.vue
> +          <span>You can change the selected office to discover the team in other offices.
Could be an alert, would be better

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/filters.vue
> +            </v-autocomplete>
If the label is`Office` why we named the variable `country/countries`?
```suggestion
            <v-autocomplete v-model="office" :items="offices" label="Office" @update:model-value="handleCountryChange"
              return-object item-title="country">
            </v-autocomplete>
```

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/filters.vue
> +  props: ["countries"],
Same here

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/filters.vue
> +    return {
Same here and please do lint to the whole file

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/personalInformation.vue
> +                country.value = props.user.location?.country;
You can load the data from 
```suggestion
                country.value = props.user.location?.name;
```
instead

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/profileImage.vue
> +      <span class="text-h5 text-uppercase">{{ fullName? avatar : "??" }}</span>
I understand why you did that. Maybe it's because the testing user `admin@gmail.com` doesn't have a full name attribute, but that's not the case. Each user must have a full name, so you can take the first two characters from the email instead of putting `??`.

also please display the background color in case the user doesn't have a profile image

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/profileImage.vue
> +      return "??";
You can do here something like that 
```suggestion
      if (props.fullName) {
        let val = String(props.fullName);
        return val.charAt(0);
      }
      return props.email[0] + props.email[1];
```

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/userCard.vue
> +      <profileImage  v-show="user" :image="user?.image" :fullName="user?.full_name"/>
i think passing the whole user object will be better

```suggestion
      <profileImage  v-show="user" :user="user" />
```

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/components/userCard.vue
> +        {{ user.location.country }}</v-card-text>
Office name instead

2024-01-23 21:44 UTC, mahmoud-emad commented on client/src/views/ProfileView.vue
> +        console.log(data.id);
Please remove this line if it is not needed. Also, I don't know why the data is printing multiple times.

![image](https://github.com/codescalers/CSHR/assets/57001890/0c848c6e-e11b-4b0d-bd60-2c8ab6894172)

2024-01-23 21:44 UTC, Mahmoud-Emad commented
Please merge the base branch

2024-01-24 09:26 UTC, Mahmoud-Emad approved these changes

2024-01-24 09:28 UTC, merged