Allow admin to update vacation request
codescalersinternships/CSHR pull request #453
Opened 2024-07-14 13:54 UTC by zaelgohary

### Description

Allow admin to update vacation request

### Related Issues

- https://github.com/codescalers/CSHR/issues/397

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-07-15 08:16 UTC, Mahmoud-Emad requested changes

2024-07-15 08:16 UTC, Mahmoud-Emad commented on client/src/components/cards/vacationCard.vue
> +          if (props.vacation.isUpdated && user.value.fullUser.id == props.vacation.applying_user || user.value.fullUser.user_type != "User" ) {
Why?

2024-07-15 08:16 UTC, Mahmoud-Emad commented on client/src/components/cards/vacationCard.vue
> +        :disabled="!form?.isValid" @click="updateVacation" v-if="vacation.applying_user.id !== user?.id">Update</v-btn>
You should only allow admins who are working in the same office.

2024-07-15 08:19 UTC, zaelgohary commented on client/src/components/cards/vacationCard.vue
> +          if (props.vacation.isUpdated && user.value.fullUser.id == props.vacation.applying_user || user.value.fullUser.user_type != "User" ) {
So any one with supervisor or admin rule could edit.

2024-07-15 08:26 UTC, zaelgohary commented on client/src/components/cards/vacationCard.vue
> +        :disabled="!form?.isValid" @click="updateVacation" v-if="vacation.applying_user.id !== user?.id">Update</v-btn>
done.

2024-07-15 13:42 UTC, Mahmoud-Emad requested changes

2024-07-15 13:42 UTC, Mahmoud-Emad commented on client/src/components/cards/vacationCard.vue
> +          if (props.vacation.isUpdated && user.value.fullUser.id == props.vacation.applying_user || user.value.fullUser.user_type != "User" ) {
The user also could update while the status of the request is pending

2024-07-15 13:42 UTC, Mahmoud-Emad commented on client/src/components/cards/vacationCard.vue
> +        :disabled="!form?.isValid" @click="updateVacation" v-if="vacation.applying_user.id !== user?.id && user?.fullUser.location.id == vacation.applying_user.location.id">Update</v-btn>
Here are some cases you want to cover

1. if the requested user type is Admin: You need to make sure that the office is the same applier office.
2. if the requested user type is Supervisor: You need to check the approvals array and if the ID is included.
3. if the requested user type is User: You have to make sure that the applier ID is the same as the requested user ID.

2024-07-16 06:23 UTC, zaelgohary commented on client/src/components/cards/vacationCard.vue
> +        :disabled="!form?.isValid" @click="updateVacation" v-if="vacation.applying_user.id !== user?.id && user?.fullUser.location.id == vacation.applying_user.location.id">Update</v-btn>
> Here are some cases you want to cover
> 1. if the requested user type is Admin: You need to make sure that the office is the same applier office. 

Already applied.

> 2. if the requested user type is Supervisor: You need to check the approvals array and if the ID is included.

Working on it.

> 3. if the requested user type is User: You have to make sure that the applier ID is the same as the requested user ID. 

Already applied.

2024-07-16 06:24 UTC, zaelgohary commented on client/src/components/cards/vacationCard.vue
> +          if (props.vacation.isUpdated && user.value.fullUser.id == props.vacation.applying_user || user.value.fullUser.user_type != "User" ) {
and that's what's applied.

2024-07-18 12:30 UTC, Mahmoud-Emad commented
please merge development

2024-07-18 12:31 UTC, Mahmoud-Emad commented
Could be only one button to update
![image](https://github.com/user-attachments/assets/affa7c6d-c274-463d-bae5-8a6b443b9f93)

2024-07-18 12:33 UTC, Mahmoud-Emad commented
The dates have not changed 

![image](https://github.com/user-attachments/assets/f7489963-54f8-449a-bcce-63df9b4b0050)
![image](https://github.com/user-attachments/assets/9d9ab13d-18cb-4f55-959f-664fefbf7434)

2024-07-18 13:26 UTC, zaelgohary commented
> Could be only one button to update ![image](https://private-user-images.githubusercontent.com/57001890/349954805-affa7c6d-c274-463d-bae5-8a6b443b9f93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDkzNzcsIm5iZiI6MTcyMTMwOTA3NywicGF0aCI6Ii81NzAwMTg5MC8zNDk5NTQ4MDUtYWZmYTdjNmQtYzI3NC00NjNkLWJhZTUtOGE2YjQ0M2I5ZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzMjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOGVhMTIyNmZjNzQxOTRhMzQ4NjRmNmFjY2E3OGVkMGY1MzA3YTBjY2M1NjhhODkwNzdjZGVhYWI0Y2MwNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qAEZC4YTbwwYk3nIpIQwUdeMyZ682wdLOEagVtyUoCA)

How to reproduce this?

2024-07-18 13:27 UTC, zaelgohary commented
> The dates have not changed
> 
> ![image](https://private-user-images.githubusercontent.com/57001890/349955177-f7489963-54f8-449a-bcce-63df9b4b0050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDkzNzcsIm5iZiI6MTcyMTMwOTA3NywicGF0aCI6Ii81NzAwMTg5MC8zNDk5NTUxNzctZjc0ODk5NjMtNTRmOC00NDlhLWJjY2UtNjNkZjliNGIwMDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzMjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmM2ZGZkODM0MTU5MjZiMDViYTJmZjFkODZiOGJjYTQzYzBmYWM5YzM1MTczOWI5NTQ5MTY0ZjI2NmRlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vnObko62HX4G5Ll6Gx5PObuM2qqQ7CHeByum6deC124) ![image](https://private-user-images.githubusercontent.com/57001890/349955274-9d9ab13d-18cb-4f55-959f-664fefbf7434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDkzNzcsIm5iZiI6MTcyMTMwOTA3NywicGF0aCI6Ii81NzAwMTg5MC8zNDk5NTUyNzQtOWQ5YWIxM2QtMThjYi00ZjU1LTk1OWYtNjY0ZmVmYmY3NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzMjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMWJiNGNjNmJkNmEzOTAwZTQ1NDFhMzhhNzkwNWE4YmZjOTM4YWMxMzI3MzRlNGRiMTAzMjJkNDA5MmMzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MIz-cnuv5PgKJa4PWISjs57_v-czetH5-p0C2NkgOoY)

Already fixed [here](https://github.com/codescalers/CSHR/pull/461)

2024-07-21 07:09 UTC, Mahmoud-Emad commented
> > The dates have not changed
> > ![image](https://private-user-images.githubusercontent.com/57001890/349955177-f7489963-54f8-449a-bcce-63df9b4b0050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDkzNzcsIm5iZiI6MTcyMTMwOTA3NywicGF0aCI6Ii81NzAwMTg5MC8zNDk5NTUxNzctZjc0ODk5NjMtNTRmOC00NDlhLWJjY2UtNjNkZjliNGIwMDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzMjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMmM2ZGZkODM0MTU5MjZiMDViYTJmZjFkODZiOGJjYTQzYzBmYWM5YzM1MTczOWI5NTQ5MTY0ZjI2NmRlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vnObko62HX4G5Ll6Gx5PObuM2qqQ7CHeByum6deC124) ![image](https://private-user-images.githubusercontent.com/57001890/349955274-9d9ab13d-18cb-4f55-959f-664fefbf7434.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDkzNzcsIm5iZiI6MTcyMTMwOTA3NywicGF0aCI6Ii81NzAwMTg5MC8zNDk5NTUyNzQtOWQ5YWIxM2QtMThjYi00ZjU1LTk1OWYtNjY0ZmVmYmY3NDM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEzMjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMWJiNGNjNmJkNmEzOTAwZTQ1NDFhMzhhNzkwNWE4YmZjOTM4YWMxMzI3MzRlNGRiMTAzMjJkNDA5MmMzYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MIz-cnuv5PgKJa4PWISjs57_v-czetH5-p0C2NkgOoY)
> 
> Already fixed [here](https://github.com/codescalers/CSHR/pull/461)

I think it shouldn't be added here

2024-07-22 13:06 UTC, Mahmoud-Emad approved these changes

2024-07-22 13:34 UTC, merged