Remove incorrect condition in calculateTimes
codescalersinternships/CSHR pull request #454
Opened 2024-07-15 12:32 UTC by zaelgohary

### Changes

- Remove incorrect condition in calculateTimes

### Related Issues

- https://github.com/codescalers/CSHR/issues/452

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-07-15 13:46 UTC, Mahmoud-Emad requested changes

2024-07-15 13:46 UTC, Mahmoud-Emad commented on client/src/components/requests/leaveRequest.vue
> +      return days
What about this case

![image](https://github.com/user-attachments/assets/f29aae82-e52e-4053-95a8-d38a9e7b6e28)

2024-07-16 06:14 UTC, zaelgohary commented on client/src/components/requests/leaveRequest.vue
> +      return days
What was being implemented is that only in cases like .25, .5, or .75 would the results be shown correctly. other than that, it would return 1 even if the result is less than 1, which is incorrect. I just fixed the return value.

2024-07-16 06:40 UTC, Mahmoud-Emad commented on client/src/components/requests/leaveRequest.vue
> +      return days
Yes, I think we need to round the value also.

2024-07-16 07:30 UTC, zaelgohary commented on client/src/components/requests/leaveRequest.vue
> +      return days
Done.

2024-07-18 12:27 UTC, Mahmoud-Emad approved these changes

2024-07-18 12:57 UTC, merged