feat: Implemented a new vacation request cancellation feature
codescalersinternships/CSHR pull request #455
Opened 2024-07-15 13:33 UTC by Mahmoud-Emad

### Changes

- Updated the `STATUS_CHOICES` class.
- Created an endpoint to update the status of the request to `request_to_cancel` status.
- Added the required validation on the view handler.
- Updated the UI to display the button the cancelation only If the requested user is the applier, and the status is still pending.
- Pushed a notification for the leaders to notify them by the request.
- Working on supporting the real-time request updater.

### Related Issues

- https://github.com/codescalers/CSHR/issues/430

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-07-18 07:51 UTC, zaelgohary commented on client/src/clients/api/vacations.ts
> +  }
All user roles should be able to cancel their pending request.

2024-07-18 09:03 UTC, zaelgohary requested changes
Nice work, @Mahmoud-Emad! just some enhanements that need to be taken into consideration.

- Request should have final action once approval user approve/cancel. (no need for user intervention)
- Approval user should be able to take approve/cancel from the notification
- Approval user data  in notification is incorrect

2024-07-18 09:03 UTC, zaelgohary commented on client/src/clients/api/vacations.ts
>    }
Whenever user tries to cancel his approved vacation he gets this:
You do not have permission to perform this action.

2024-07-18 11:24 UTC, Mahmoud-Emad commented
> Nice work, @Mahmoud-Emad! just some enhanements that need to be taken into consideration.
> 
> * Request should have final action once approval user approve/cancel. (no need for user intervention)
> * Approval user should be able to take approve/cancel from the notification
> * Approval user data  in notification is incorrect

All cases covered!

2024-07-21 07:28 UTC, zaelgohary approved these changes

2024-07-21 07:37 UTC, merged