Check pending requests dates before post/put request
codescalersinternships/CSHR pull request #459
Opened 2024-07-17 08:14 UTC by zaelgohary

### Description

Describe the changes introduced by this PR and what does it affect

### Changes

Check for date range instead of checking for start & end date only

### Related Issues

- https://github.com/codescalers/CSHR/issues/378

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings
- [ ] Screenshots/Video attached (needed for UI changes)

2024-07-18 12:26 UTC, Mahmoud-Emad requested changes

2024-07-18 12:26 UTC, Mahmoud-Emad commented on server/cshr/views/vacations.py
> +                )
You don't need to do for loop on a database transaction, you could easily filter based on your dates

```suggestion
                pending_requests = Vacation.objects.filter(
                    from_date__lte__in=date_range,
                    end_date__gte__in=date_range,
                    status=STATUS_CHOICES.PENDING,
                    applying_user=applying_user,
                )
```

2024-07-18 12:26 UTC, Mahmoud-Emad commented on server/cshr/views/vacations.py
> +                )
Same here

2024-07-18 13:16 UTC, zaelgohary commented on server/cshr/views/vacations.py
> +                )
The suggested code gave me an error. I removed the loop and changed the query to check for overlapping dates to get the range.

2024-07-21 06:57 UTC, Mahmoud-Emad approved these changes

2024-07-21 07:10 UTC, merged