resolve issue #59 to improve custom response methods
codescalersinternships/CSHR pull request #60
Opened 2022-08-19 14:58 UTC by 0oM4R

- remove custom response of Delete method , we can use success with status code 204 instead 
- replace message with a dictionary of message in return, that caused errors in CRUD development

2022-08-21 10:42 UTC, Mahmoud-Emad requested changes

2022-08-21 10:42 UTC, Mahmoud-Emad commented on server/cshr/api/response.py
> +        return Response({"message": message}, status=status_code)
Can you please explain it to me !!, why should we use Dict instead of Str?

2022-08-21 10:42 UTC, Mahmoud-Emad commented on server/cshr/api/response.py
> +        return Response({"message": message}, status=status_code)
Can you please explain it to me !!, why should we use Dict instead of Str?

2022-08-22 09:13 UTC, 0oM4R commented on server/cshr/api/response.py
> +        return Response({"message": message}, status=status_code)
in the case using Str we got this error 
![Screenshot from 2022-08-22 11-04-34](https://user-images.githubusercontent.com/62248851/185883904-3bb30956-720e-4491-a001-7ad9b716b5aa.png)
also, there is no indication of a message argument in [docs](https://www.django-rest-framework.org/api-guide/responses/#creating-responses), it's only `(data, status=None, template_name=None, headers=None, content_type=None)`

2022-08-22 09:14 UTC, 0oM4R commented on server/cshr/api/response.py
> +        return Response({"message": message}, status=status_code)
in the case using Str we got this error 
![Screenshot from 2022-08-22 11-04-34](https://user-images.githubusercontent.com/62248851/185883904-3bb30956-720e-4491-a001-7ad9b716b5aa.png)
also, there is no indication of a message argument in [docs](https://www.django-rest-framework.org/api-guide/responses/#creating-responses), it's only `(data, status=None, template_name=None, headers=None, content_type=None)`

2022-08-22 09:31 UTC, Mahmoud-Emad approved these changes

2022-08-22 09:31 UTC, merged