Development user endpoints
codescalersinternships/CSHR pull request #87
Opened 2022-09-01 11:15 UTC by aliasaddik

* implemented all user end point for all types of users  (normal user , admin , supervisor and viewing self profiles)
* implemented adding skills for a user endpoint
* * please re-check that the fields that can be viewed and updated by each type of user is consistent with the requirements

2022-09-03 16:33 UTC, Mahmoud-Emad requested changes

2022-09-03 16:33 UTC, Mahmoud-Emad commented on config/.env.template
> +DJANGO_CORS_ALLOW_ORIGIN_DEVELOPMENT=https://localhost:3000
We don't need Django-cors yet.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/models/evaluations.py
> +    def str(self) -> str:
when you use the `str` method in side a database object just call `__str__` instead of `str`, e.g. you wanna get the name of an object, so when you implement `__str__` method the result you will see the actual name of this object, if not you will see the address of the object.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/models/evaluations.py
> +    def str(self) -> str:
same here.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/routs/training_courses.py
> +from ..views.training_courses import TrainingCoursesAPIView
use full path when you import anything inside the project.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/routs/training_courses.py
> +    path("", TrainingCoursesAPIView.as_view({"post": "post"})),
Why here do we have 2 routes? it can be done with just one.
```suggestion
    path("", TrainingCoursesAPIView.as_view({"get": "get_all", "post": "post"})),
```

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/routs/users.py
> +    path("adminView/", AdminUserAPIView.as_view({"get": "get_all"})),
also here we don't have to use any camel case type.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/auth.py
> +
We already have `image_field` inside the user table, so why do we reuse Drf one?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/auth.py
> +            "image",
1 - too many lines, can be done in 2 lines
2 - remove field `image` from fields and use UserModel one.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +# from server.cshr.models.office import Office
if you don't wanna these imports remove them.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +# from server.cshr.serializers.office import OfficeSerializer
if you don't wanna these imports remove them.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +            "created_at",
too many lines.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +    # user_evaluation = SerializerMethodField()
remove this line if not needed.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +            # "user_evaluation",
too many lines, also remove the last one if it is not needed.
#### Hint:
* It's pretty to comment on things in separate lines, comments inside `[]`, `()`, `{}` not pretty good.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +    #     return EvaluationSerializer(evaluations, many=True).data
also, if we do not use it why do we keep it?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +    # user_evaluation = SerializerMethodField()
also, if we do not use it why do we keep it?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +    #     return UserSkillsSerializer(skills, many=True).data
1 - too many lines.
2 - if we do not use it why do we keep it?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +    #     return EvaluationSerializer(evaluations, many=True).data
also, if we do not use it why do we keep it?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +    # user_evaluation = SerializerMethodField(read_only=True)
also, if we do not use it why do we keep it?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +            # "user_evaluation",
1 - too many lines.
2 - if we do not use it why do we keep it?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/serializers/users.py
> +    #     return EvaluationSerializer(evaluations, many=True).data
if we do not use it why do we keep it?

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/services/users.py
> +        return None
we can write this logic inside its service file, implement a function called `user_search` then use it.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/tests/test_auth.py
> +
Please see Andrew's updates and re-update your unit tests.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/tests/test_auth.py
>          self.assertEqual(response.status_code, status.HTTP_200_OK)
also here.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/views/training_courses.py
> +            )
1- We have a service file that can make this logic inside.
2- When we use `all()` or `filter()` it's not required to make `try, catch`  because when receiving empty data like `[]` it's okay to return it.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/views/training_courses.py
> +            return CustomResponse.not_found()
put it inside its service.

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/views/training_courses.py
> +            return CustomResponse.not_found(message="Training course not found")
same here, also I think it will fail, did you try to test it? you receive the `id` param as a string and the actual type of the id field is an integer

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/views/training_courses.py
> +            return CustomResponse.not_found(message="Training course not found")
same

2022-09-03 16:33 UTC, Mahmoud-Emad commented on server/cshr/views/users.py
> +# from server.cshr.models.skills import Skills
.

2022-09-04 07:31 UTC, aliasaddik commented on server/cshr/serializers/users.py
> +    # user_evaluation = SerializerMethodField()
the evaluation model was edited so I commented all my usage of it until fix them and deal with the changes

2022-09-04 19:41 UTC, Mahmoud-Emad commented
@aliasaddik 
There is a conflict, can you please fix it?

2022-09-05 10:32 UTC, merged